### ISSUE TITLE
I have Re-published this extension. 

### ISSUE THREAD

**Issue by faldor20** [fsprojects/fsharp-language-server#100]
After seeing an extended period of inactivity and amassing a large number of changes i have re-published this extension from this fork:
https://github.com/faldor20/fsharp-language-server
The updated extension is here
https://marketplace.visualstudio.com/items?itemName=faldor20.fsharp-language-server-updated

**Comment by arafatamim** [comment]
Nice! Thanks for this

**Comment by faldor20** [comment]
Now that i am maintaining this extension, my version will be removed
