### ISSUE TITLE
Any plans for extra features?

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/fsharp-language-server#18]
such as:
* semantic highlighting e.g. highlighting mutable or custom operations etc
* code lens for function signatures
* any other lsp aspect that could be generated via the FCS API

**Comment by georgewfraser** [comment]
Hmm, I've been really focused on making the core features fast, performant, and zero-configuration. If you look at recent issues it's mostly corner-cases of project files and things like that https://github.com/georgewfraser/fsharp-language-server/pull/17 https://github.com/georgewfraser/fsharp-language-server/issues/8

Semantic highlighting would be super cool but I'm not sure the language server protocol provides a mechanism to support it yet.

I have to say that I personally find code lens for function signatures annoying, but if someone submitted a PR for that I would accept it.

I'm pretty sure all the relevant LSP features are supported, do you see something missing?

I'd also like to get good instructions/packaging in here for running on Vim, Emacs, Sublime, but I don't use those editors so I'm really looking for help on that.

**Comment by ronaldschlenker** [comment]
For me, code lens is annoying, too. But the line lens feature of Ionide, I don’t want to miss that anymore.

**Comment by qcc-na** [comment]
I think code lens support is a good idea, it can always be turned off for those who don't like it.
