### ISSUE TITLE
Errors being shown when there are none.

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/fsharp-language-server#19]
![screen shot 2018-08-30 at 12 29 33](https://user-images.githubusercontent.com/588746/44848968-81cf2e80-ac50-11e8-8bfe-d824c4f8292d.png)

Seems to be an artefact of project cracking where incorrect references are being resolved

**Comment by 7sharp9** [comment]
For example:
```
Error rendering tooltip: The type referenced through 'System.ArraySegment`1' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard'.
```

This is a netcoreapp project referencing a netstandard project

**Comment by 7sharp9** [comment]
full log is here if its any use: https://gist.github.com/7sharp9/956e471533428a7a43f2e407aed3d8e9

**Comment by georgewfraser** [comment]
Project cracking is the *hardest* part. The rules of `.fsproj` and the implementational details of the whole .net toolchain are a de-facto under-specified part of F#.

If you could create a minimal project that reproduces this error, that would really help to diagnose, and we can add it to the test suite---there's a bunch already in sample/

**Comment by georgewfraser** [comment]
There's been a lot of small fixes to project cracking in the last 6 months---perhaps this particular project works now? 

If your project still doesn't crack, the most helpful thing is if you can make a minimal example. We've got a good collection of "hard-to-crack" projects in https://github.com/fsprojects/fsharp-language-server/tree/master/sample and we can always use more 😄
