### ISSUE TITLE
Run & Debug tests: Xunit possible?

### ISSUE THREAD

**Issue by hoetz** [fsprojects/fsharp-language-server#46]
What would it take to get xunit tests decorated with [Fact] et al. to work with the debug test command?

**Comment by hoetz** [comment]
Ok, adding "Fact" here is a first step and on my local dev version the tests already show up. dotnet test starts but it's waiting for the debugger to attach but it never does 🤔

https://github.com/fsprojects/fsharp-language-server/blob/cff4c38fa7172c1f458aeac603d7c29ad90f15d1/src/FSharpLanguageServer/Program.fs#L127


![image](https://user-images.githubusercontent.com/3835948/52786016-f4df2c80-3059-11e9-869c-e53dc2b8f5bf.png)

**Comment by georgewfraser** [comment]
The `Debug Test` command works now, it just starts paused, so you have to press play. For some reason it was very complicated to change this behavior, I don't totally remember why. 

Obviously it would be better if it starts unpaused, or if it at least pops up a message telling you.

**Comment by georgewfraser** [comment]
The "Debug Test" code lens issues a custom notification that invokes this function:

https://github.com/fsprojects/fsharp-language-server/blob/cff4c38fa7172c1f458aeac603d7c29ad90f15d1/client/extension.ts#L83

So it's basically just a question of making that function support xunit.

**Comment by georgewfraser** [comment]
Also, the debugger starts paused for some complicated reason that I forget. So you may just need to press play...it would be nice if that were not necessary, obviously.

**Comment by hoetz** [comment]
Indeed, pressing "play" worked :)
The pull request I submitted provides support for Fact / Theory tests and is certified "works on my machine"

**Comment by hoetz** [comment]
For future reference, this is how omnisharp implements test detection 
https://github.com/OmniSharp/omnisharp-roslyn/tree/6836fadb9c35a88d4695276d14302336a460b841/src/OmniSharp.DotNetTest/TestFrameworks

**Comment by georgewfraser** [comment]
The problem with that approach is you have to parse *and* typecheck the code, and typechecking takes time, especially in F#. Code lenses need to be computed fast, so we have to figure out how to find the test methods by just parsing the code.
