### ISSUE TITLE
Facing problem opening an big project

### ISSUE THREAD

**Issue by kunjee17** [fsprojects/fsharp-language-server#59]
I was trying this extension with [GreenPrint](https://github.com/kunjee17/greenprint) project. And it just couldn't start and crashing multiple times then stops working. 

Can you please help me with this ? or at least let me know how to get debug trace.

**Comment by PhilT** [comment]
Is this in VSCode or Vim? I've just opened in Neovim and it's working fine. Of course just looking at the date this may no longer be an issue.

**Comment by kunjee17** [comment]
It should closed I guess. I was using VSCode. I m closing issue for now.
