### ISSUE TITLE
vscode no longer show intellisense descriptions

### ISSUE THREAD

**Issue by faldor20** [fsprojects/fsharp-language-server#80]
I have noticed recently the littile show description button in the intellisense window is gone and never automatically appears. This is a big problem for me because I'm still learning and that window was by far the best way to pick things like list functions without looking up documentation.

**Comment by faldor20** [comment]
Oh and just incase soemone mentions ionide. It is so slow and buggy that even with all its handy features it is basically unusable

**Comment by georgewfraser** [comment]
That is very strange. Can you open the output pane and show what appears under "FSharp Language Server"?
