### ISSUE TITLE
No auto completion support for .net build-in types in Visual Studio Code

### ISSUE THREAD

**Issue by dmrysev** [fsprojects/fsharp-language-server#89]
![image](https://user-images.githubusercontent.com/20811477/108248962-23b69e80-715d-11eb-95eb-4bd717513cc8.png)

**Comment by dmrysev** [comment]
![image](https://user-images.githubusercontent.com/20811477/108249165-67110d00-715d-11eb-8d70-105c5d37707b.png)

**Comment by faldor20** [comment]
This woks now, see #101
