### ISSUE TITLE
Error "Namespace is not defined" when using project reference which share the same namespace root

### ISSUE THREAD

**Issue by MangelMaxime** [fsprojects/fsharp-language-server#96]
Hello,

I have the following architecture:

- `Library.Base.fsproj` with a namespace `Library.Base`
- `Library.Base.Implementation.fsproj` with a namespace `Library.Base.Implementation` and this project reference `Library.Base.fsproj`
- `reproduction_fsharp_lsp.fsproj` reference `Library.Base.Implementation.fsproj`

The problem is that this Fsharp language server report `Library.Base.Implementation` as not defined in `reproduction_fsharp_lsp.fsproj`

![image](https://user-images.githubusercontent.com/4760796/116818028-8bc82e80-ab69-11eb-8c39-5932eb6956ad.png)

When executing `dotnet build` the project works fine and others IDEs like Rider, VS and Ionide doesn't report the error.

**Reproduction**

1. `git clone git@github.com:MangelMaxime/FSharp.Language.Server---Reproduction-1.git`
2. Open the project in VSCode
3. Open `Library.fs`
4. See the error on `open Library.Base.Implementation` line

Note: In order to have `dotnet build` to work you need to close VSCode see #95 for more information about this bug

**Comment by faldor20** [comment]
Hey i just updated the readme sorry about the confusion 
"Untill I can sort out access to publishing new versions of the original extension, this is the working version of this extension [F# Language Server updated](https://marketplace.visualstudio.com/items?itemName=faldor20.fsharp-language-server-updated)"

Could you test with that version?

**Comment by MangelMaxime** [comment]
Hello @faldor20,

the error is still occurring for me.

**Comment by faldor20** [comment]
I believe this was a problem related to buildalyzer which was replaced in this version https://github.com/fsprojects/fsharp-language-server/commit/51d521569a1bc3575806d20ba5e33e88c3dfa1be
Either way I can no longer reproduce this error so I think it should be sorted.
Sorry it took so long 😅
